name: Deploy Develop Theme

on:
  push:
    pull_request: null
    branches:
      - develop

jobs:
  deploy:
    name: Deploy Develop Theme
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Install dependencies
        run: npm i

      - name: Build
        run: npm run build

      - uses: pgrimaud/action-shopify@2.1.3
        env:
          SHOPIFY_PASSWORD: ${{ secrets.SHOPIFY_DEVELOP_PASSWORD }}
          SHOPIFY_STORE_URL: ${{ secrets.SHOPIFY_DEVELOP_STORE_URL }}
          SHOPIFY_THEME_ID: ${{ secrets.SHOPIFY_DEVELOP_THEME_ID }}
          THEME_PATH: ./dist/
        with:
          args: --ignored-file=config/settings_data.json